CREATE TABLE CUSTOMERS (
    CUSTOMER_ID     NUMBER,
    FIRST_NAME      VARCHAR2(50 BYTE),
    LAST_NAME       VARCHAR2(50 BYTE),
    EMAIL_ADDRESS   VARCHAR2(50 BYTE)
);

CREATE UNIQUE INDEX PK_CUSTOMER_ID ON
    CUSTOMERS (
        CUSTOMER_ID
    );

ALTER TABLE CUSTOMERS ADD (
    CONSTRAINT PK_CUSTOMER_ID PRIMARY KEY ( CUSTOMER_ID )
        USING INDEX PK_CUSTOMER_ID
);


CREATE TABLE EVENT (
    EVENT_ID          NUMBER,
    EV_CATEGORY       VARCHAR2(50 BYTE),
    EV_SUB_CATEGORY   VARCHAR2(50 BYTE),
    EVENT_NAME        VARCHAR2(100 BYTE),
    EVENT_DATE 	      TIMESTAMP,
    ONSALE_DATE       TIMESTAMP
);

CREATE UNIQUE INDEX PK_EVENT_ID ON
    EVENT (
        EVENT_ID
    );

ALTER TABLE EVENT ADD (
    CONSTRAINT PK_EVENT_ID PRIMARY KEY ( EVENT_ID )
        USING INDEX PK_EVENT_ID
);


CREATE TABLE ORDERS (
    ORDER_ID        NUMBER,
    CUSTOMER_ID     NUMBER,
    EVENT_ID        NUMBER,
    ORDER_DATE      TIMESTAMP,
    PHONE_ORDER     VARCHAR2(1 BYTE),
    MOBILE_DEVICE   VARCHAR2(1 BYTE),
    EMAIL_ADDRESS   VARCHAR2(50 BYTE),
    ORDER_TOTAL     NUMBER(10, 2)
);

CREATE UNIQUE INDEX PK_ORDER_ID ON
    ORDERS (
        ORDER_ID
    );

ALTER TABLE ORDERS ADD (
    CONSTRAINT PK_ORDER_ID PRIMARY KEY ( ORDER_ID )
        USING INDEX PK_ORDER_ID
);

ALTER TABLE ORDERS ADD (
    CONSTRAINT FK_CUSTOMER_ID FOREIGN KEY ( CUSTOMER_ID )
        REFERENCES CUSTOMERS ( CUSTOMER_ID ),
    CONSTRAINT FK_EVENT_ID FOREIGN KEY ( EVENT_ID )
        REFERENCES EVENT ( EVENT_ID )
);